# Generated by Django 5.0.1 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_is_acti_bab322_idx',
            old_name='api_event_is_acti_b43e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_event_t_6adc27_idx',
            old_name='api_event_event_t_5b3e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_is_feat_e0ae61_idx',
            old_name='api_event_is_feat_97f42e_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_start_d_a1f367_idx',
            old_name='api_event_start_d_3f7d8a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_status_c91afb_idx',
            old_name='api_event_status_e4b9c2_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='formatted_price',
            field=models.CharField(blank=True, help_text="Formatted price display (e.g., 'No Cover', '$10 Cover', '$65 per person')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_days',
            field=models.CharField(blank=True, help_text="Days of week for recurring events (e.g., 'thursday', 'friday,saturday')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_type',
            field=models.CharField(choices=[('none', 'One Time Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='How often this event occurs', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_until',
            field=models.DateField(blank=True, help_text='End date for recurring events', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special instructions (legacy field)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_required',
            field=models.BooleanField(default=False, help_text='Whether booking is required for this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_url',
            field=models.URLField(blank=True, help_text='URL for booking this event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('once', 'One Time Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', help_text='How often this event occurs (legacy field)', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees (legacy field)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_display',
            field=models.CharField(blank=True, help_text='Custom price display (legacy field)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_day',
            field=models.CharField(blank=True, help_text='Day of week for recurring events (legacy field)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Event status', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('interior', 'Interior Design'), ('events', 'Events & Celebrations'), ('cocktails', 'Cocktails'), ('atmosphere', 'Atmosphere'), ('other', 'Other')], default='other', help_text='Category for organizing gallery items', max_length=20),
        ),
    ]
