# Generated by Django 5.0.1 on 2025-12-29 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menucategory_menuitem_menuitemvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Floor plan name (e.g., 'Main Dining', 'Patio')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this floor plan')),
                ('display_order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Is this floor plan active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('discount', 'Discount'), ('freebie', 'Freebie'), ('upgrade', 'Upgrade')], default='discount', max_length=20)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses_total', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text="Source model type (e.g., 'menu_item', 'gallery_item')", max_length=50)),
                ('source_id', models.UUIDField(help_text='Source model UUID')),
                ('image', models.ImageField(upload_to='processed/')),
                ('format', models.CharField(choices=[('webp', 'WebP'), ('avif', 'AVIF'), ('jpeg', 'JPEG')], max_length=10)),
                ('size', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge')], max_length=20)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('blur_hash', models.CharField(blank=True, max_length=100)),
                ('lqip_data_url', models.TextField(blank=True, help_text='Low Quality Image Placeholder (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='api_process_source__9faeeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('confirmation', 'Reservation Confirmation'), ('reminder', 'Reservation Reminder'), ('otp', 'OTP Verification'), ('marketing', 'Marketing')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(help_text="Table number (e.g., 'T1', 'VIP-1')", max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum capacity')),
                ('min_capacity', models.IntegerField(default=1, help_text='Minimum capacity')),
                ('shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('rectangular', 'Rectangular'), ('booth', 'Booth')], default='square', max_length=20)),
                ('position_x', models.IntegerField(blank=True, help_text='X coordinate for visual layout', null=True)),
                ('position_y', models.IntegerField(blank=True, help_text='Y coordinate for visual layout', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is table currently available')),
                ('is_vip', models.BooleanField(default=False, help_text='Is this a VIP table')),
                ('notes', models.TextField(blank=True, help_text='Special notes about this table')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.floorplan')),
            ],
            options={
                'ordering': ['floor_plan', 'table_number'],
                'unique_together': {('floor_plan', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('regular', 'Regular'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('vip', 'VIP')], default='regular', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('lifetime_visits', models.IntegerField(default=0)),
                ('lifetime_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dietary_preferences', models.TextField(blank=True)),
                ('special_occasions', models.JSONField(blank=True, default=dict)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.table')),
            ],
            options={
                'ordering': ['-lifetime_spent', '-lifetime_visits'],
            },
        ),
        migrations.CreateModel(
            name='TableAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_assignments', to='api.reservation')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.table')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('membership_number', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_membership', to='api.customerprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('party_size', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('seated', 'Seated'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('estimated_wait_minutes', models.IntegerField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customerprofile')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
