# Generated by Django 5.2.7 on 2026-01-05 13:06

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_floorplan_offer_otpverification_processedimage_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('is_published', models.BooleanField(default=False, help_text='Published to public site')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('story', 'Our Story'), ('signature_picks', 'Signature Picks'), ('tonights_vibe', "Tonight's Vibe"), ('upcoming_events', 'Upcoming Events'), ('gallery_preview', 'Gallery Preview'), ('reviews', 'Reviews Carousel'), ('visit', 'Visit Section'), ('location', 'Location Section'), ('final_cta', 'Final CTA'), ('custom', 'Custom Section')], help_text='Type of homepage section', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Section subtitle', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Section description/content')),
                ('button_text', models.CharField(blank=True, help_text='CTA button text', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='CTA button URL', max_length=300)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.home_section_image_path)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=api.models.home_section_image_path)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional section data')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('display_order', models.IntegerField(default=0, help_text='Order on page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('is_published', models.BooleanField(default=False, help_text='Published to public site')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Bottle Brothers', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Albania', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Info',
                'verbose_name_plural': 'Restaurant Info',
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('is_published', models.BooleanField(default=False, help_text='Published to public site')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('contact', 'Contact Page'), ('about', 'About Page'), ('reservations', 'Reservations Page'), ('events', 'Events Page'), ('menu', 'Menu Page'), ('gallery', 'Gallery Page'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service')], max_length=50, unique=True)),
                ('page_title', models.CharField(max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Main page content (Markdown supported)')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Content',
                'verbose_name_plural': 'Static Content',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuespace',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to public site'),
        ),
        migrations.AddField(
            model_name='venuespace',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('locale', models.CharField(choices=[('sq', 'Albanian'), ('en', 'English')], max_length=5)),
                ('field_name', models.CharField(help_text='Name of the translated field', max_length=100)),
                ('translated_text', models.TextField(help_text='Translated content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_auto_translated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translated_by', models.CharField(blank=True, help_text='Who created this translation', max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['locale', 'field_name'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'locale'], name='api_transla_content_c885b5_idx'), models.Index(fields=['status'], name='api_transla_status_647bdd_idx')],
                'unique_together': {('content_type', 'object_id', 'locale', 'field_name')},
            },
        ),
    ]
