# Generated by Django 5.2.7 on 2026-01-05 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Conversation subject', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Client user who started the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Conversation',
                'verbose_name_plural': 'Client Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content')),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], max_length=10)),
                ('sender_name', models.CharField(help_text='Name of sender', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.clientconversation')),
            ],
            options={
                'verbose_name': 'Client Message',
                'verbose_name_plural': 'Client Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
