# Generated by Django 5.2.7 on 2026-01-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clientconversation_clientmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for main categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.menucategory'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('cocktails', 'Cocktails'), ('wine', 'Wine'), ('beer', 'Beer'), ('food', 'Food'), ('shisha', 'Shisha'), ('appetizers', 'Appetizers'), ('mains', 'Main Courses'), ('desserts', 'Desserts'), ('beverages', 'Beverages'), ('specials', "Chef's Specials")], help_text='Category type (for main categories)', max_length=20),
        ),
    ]
