# Generated by Django 5.2.7 on 2026-01-08 13:32

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_subcategory_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for the moment', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('image', models.ImageField(help_text='Moment photo', upload_to=api.models.moment_image_path)),
                ('is_active', models.BooleanField(default=True, help_text='Show this moment publicly')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moment',
                'verbose_name_plural': 'Moments',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='api_moment_is_acti_7b8dc7_idx')],
            },
        ),
    ]
